/**
 * Legacy export byte-identity tripwire.
 *
 * Covers: SC-003, SC-013, SC-022 (via NF-004) — plan phase 01, decision D6.
 *
 * `tests/fixtures/export-legacy-baseline.html` was generated by calling
 * `exportSiteToHTML` with the `baselineConfig` / `baselineSettings` objects
 * declared below (verbatim) and writing the returned string to disk unmodified.
 * The generator script was deleted afterwards; this test file is now the only
 * reproducible record of how the fixture was made.
 *
 * Provenance: `src/lib/export-html.ts` and `src/blocks/` are byte-untouched
 * versus the pre-change commit, so every byte in the fixture is genuinely
 * pre-change output. It was regenerated once more — still against that same
 * unmodified exporter — after an adversarial mutation sweep showed the first
 * version failed to pin two branch families (below). Both regenerations
 * happened before any production edit.
 *
 * The config exercises every block type that the exporter rendered BEFORE the
 * publish-fidelity work began — 13 types / 24 block instances, covering every
 * variant that has a dedicated renderer path — and deliberately freezes BOTH
 * sides of every conditional branch the later phases will touch:
 *   - `renderLink` with a url (-> `<a>`) and without one (-> `<span>`), including
 *     a whitespace-only url. Phase 02 rewrites this exact condition to
 *     `if (url && isAllowedUrl(url))`, so the non-anchor branch has to be frozen
 *     here or that change would be invisible to this tripwire.
 *   - all three `logoImage ? <img> : <div>` ternaries, true side and false side.
 *
 * Link items are STRING-only and CTA urls are https:, so a legacy string config
 * must keep round-tripping byte-identically (SC-013).
 *
 * DO NOT hand-edit the fixture, and DO NOT regenerate it to make this test pass.
 * Phase 07 re-derives it from git history if a reviewer asks.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { exportSiteToHTML } from '../src/lib/export-html'
import type { SiteConfig } from '../src/blocks/types'

const baselineConfig: SiteConfig = {
  name: 'Legacy Baseline',
  blocks: [
    {
      id: 'nav-1',
      type: 'navbar',
      variant: 'default',
      props: {
        logo: 'Acme',
        logoImage: 'https://cdn.example.com/logo.png',
        links: ['Product', 'Features', 'Pricing', 'Docs'],
        ctaText: 'Get Started',
      },
    },
    {
      // No `logoImage` — freezes the OTHER side of the navbar `logoImage`
      // ternary, so neither branch can regress silently.
      id: 'nav-2',
      type: 'navbar',
      variant: 'centered',
      props: { logo: 'Acme', links: ['Docs'], ctaText: 'Start' },
    },
    {
      // CTAs with a label but NO url — freezes the `<span>` (non-anchor) branch
      // of `renderLink`, which is exactly the branch phase 02 rewrites from
      // `if (url && url.trim())` to `if (url && isAllowedUrl(url))`. A
      // regression there cannot turn this fixture red without this block.
      id: 'hero-no-url',
      type: 'hero',
      variant: 'centered',
      props: {
        headline: 'No CTA urls',
        subheadline: 'Freezes the non-anchor renderLink branch',
        primaryCta: 'Start',
        secondaryCta: 'Learn more',
      },
    },
    {
      // A whitespace-only url — the other half of renderLink's `url.trim()`
      // condition, and a value phase 02's policy must still treat as no-url.
      id: 'hero-blank-url',
      type: 'hero',
      variant: 'split',
      props: {
        headline: 'Blank CTA url',
        primaryCta: 'Start',
        primaryCtaUrl: '   ',
        heroImage: 'https://cdn.example.com/hero-blank.png',
      },
    },
    {
      id: 'hero-1',
      type: 'hero',
      variant: 'centered',
      props: {
        badge: 'New',
        headline: 'Ship faster',
        subheadline: 'The baseline hero',
        primaryCta: 'Start',
        primaryCtaUrl: 'https://example.com/start',
        secondaryCta: 'Docs',
        secondaryCtaUrl: 'https://example.com/docs',
      },
    },
    {
      id: 'hero-2',
      type: 'hero',
      variant: 'split',
      props: {
        headline: 'Split hero',
        subheadline: 'With an image',
        primaryCta: 'Start',
        primaryCtaUrl: 'https://example.com/start',
        heroImage: 'https://cdn.example.com/hero.png',
      },
    },
    {
      id: 'hero-3',
      type: 'hero',
      variant: 'gradient',
      props: {
        headline: 'Gradient hero',
        subheadline: 'No image',
        primaryCta: 'Start',
        primaryCtaUrl: 'https://example.com/start',
      },
    },
    {
      id: 'feat-1',
      type: 'features',
      variant: 'grid',
      props: {
        label: 'Features',
        title: 'Everything you need',
        subtitle: 'A grid of three',
        items: [
          { icon: 'A', title: 'Alpha', description: 'First feature' },
          { icon: 'B', title: 'Beta', description: 'Second feature' },
          { icon: 'C', title: 'Gamma', description: 'Third feature' },
        ],
      },
    },
    {
      id: 'feat-2',
      type: 'features',
      variant: 'list',
      props: {
        label: 'Features',
        title: 'Listed features',
        items: [
          { icon: 'D', title: 'Delta', description: 'Fourth feature' },
          { icon: 'E', title: 'Epsilon', description: 'Fifth feature' },
        ],
      },
    },
    {
      id: 'price-1',
      type: 'pricing',
      variant: 'simple',
      props: {
        title: 'Pricing',
        subtitle: 'Simple tiers',
        tiers: [
          { name: 'Free', price: '$0', features: ['One thing'], ctaText: 'Start' },
          {
            name: 'Pro',
            price: '$20',
            features: ['One thing', 'Another thing'],
            ctaText: 'Go Pro',
            featured: true,
          },
        ],
      },
    },
    {
      id: 'price-2',
      type: 'pricing',
      variant: 'comparison',
      props: {
        title: 'Compare',
        tiers: [
          { name: 'Free', price: '$0', features: ['One thing'], ctaText: 'Start' },
          {
            name: 'Team',
            price: '$50',
            features: ['One thing', 'Another thing'],
            ctaText: 'Buy',
            featured: true,
          },
        ],
      },
    },
    {
      id: 'cta-1',
      type: 'cta',
      variant: 'simple',
      props: {
        headline: 'Ready?',
        subheadline: 'Join today',
        buttonText: 'Sign up',
        buttonUrl: 'https://example.com/signup',
      },
    },
    {
      id: 'cta-2',
      type: 'cta',
      variant: 'split',
      props: {
        headline: 'Still ready?',
        buttonText: 'Talk to us',
        buttonUrl: 'https://example.com/contact',
      },
    },
    {
      id: 'tst-1',
      type: 'testimonials',
      variant: 'cards',
      props: {
        title: 'Loved by teams',
        items: [
          { quote: 'Great product', name: 'Ada', role: 'CTO', rating: 5 },
          { quote: 'Works well', name: 'Grace', role: 'PM', rating: 4 },
        ],
      },
    },
    {
      id: 'stat-1',
      type: 'stats',
      variant: 'grid',
      props: {
        title: 'By the numbers',
        items: [
          { value: '1k+', label: 'Users' },
          { value: '99%', label: 'Uptime' },
        ],
      },
    },
    {
      id: 'stat-2',
      type: 'stats',
      variant: 'bar',
      props: {
        items: [
          { value: '10', label: 'Countries' },
          { value: '5', label: 'Regions' },
        ],
      },
    },
    {
      id: 'faq-1',
      type: 'faq',
      variant: 'accordion',
      props: {
        title: 'FAQ',
        items: [
          { question: 'What is it?', answer: 'A baseline fixture' },
          { question: 'Why?', answer: 'Byte-identity tripwire' },
        ],
      },
    },
    {
      id: 'team-1',
      type: 'team',
      variant: 'grid',
      props: {
        title: 'The team',
        members: [
          { name: 'Ada', role: 'CTO' },
          { name: 'Grace', role: 'PM' },
        ],
      },
    },
    { id: 'contact-1', type: 'contact',
      variant: 'form', props: { title: 'Contact', subtitle: 'Say hello' } },
    {
      id: 'news-1',
      type: 'newsletter',
      variant: 'simple',
      props: {
        title: 'Newsletter',
        buttonText: 'Subscribe',
        socialProof: 'Join 1,000 readers',
      },
    },
    {
      id: 'logo-1',
      type: 'logocloud',
      variant: 'default',
      props: { title: 'Trusted by', logos: ['Vercel', 'Stripe', 'GitHub'] },
    },
    {
      id: 'foot-1',
      type: 'footer',
      variant: 'simple',
      props: {
        logo: 'Acme',
        // With a logo image — the `true` side of the footer-simple logoImage
        // ternary. foot-2 freezes the `false` side.
        logoImage: 'https://cdn.example.com/footer-logo.png',
        copyright: '© 2026 Acme',
        links: ['Privacy', 'Terms'],
      },
    },
    {
      id: 'foot-2',
      type: 'footer',
      variant: 'multi-column',
      props: {
        // No logoImage — the `false` side of the multi-column logoImage ternary.
        logo: 'Acme',
        copyright: '© 2026 Acme',
        columns: [
          { title: 'Product', links: ['Features', 'Pricing'] },
          { title: 'Company', links: ['About', 'Careers'] },
        ],
      },
    },
    {
      id: 'foot-3',
      type: 'footer',
      variant: 'minimal',
      props: { copyright: '© 2026 Acme', links: ['Privacy', 'Terms'] },
    },
  ],
}

const baselineSettings = {
  siteName: 'Acme',
  seoTitle: 'Acme — the baseline',
  seoDescription: 'A frozen legacy export',
  language: 'English',
  faviconUrl: 'https://cdn.example.com/favicon.ico',
  ogImageUrl: 'https://cdn.example.com/og.png',
  gaId: 'G-BASELINE01',
  posthogKey: 'phc_baseline_key',
}

const FIXTURE_PATH = resolve(import.meta.dirname, 'fixtures/export-legacy-baseline.html')

describe('legacy export byte-identity (NF-004)', () => {
  it('reproduces the pre-change export byte-for-byte', () => {
    const baseline = readFileSync(FIXTURE_PATH, 'utf8')
    const actual = exportSiteToHTML(baselineConfig, { settings: baselineSettings })
    expect(actual).toBe(baseline)
  })

  it('renders no unknown-block comments for the 13 legacy types', () => {
    // Asserted against the LIVE exporter output, not the fixture: reading the
    // static file would pass even if the exporter regressed.
    const actual = exportSiteToHTML(baselineConfig, { settings: baselineSettings })
    expect(actual).not.toContain('Unknown block type')
  })
})
